// Generated by dia2code
#ifndef SERVER__USER__H
#define SERVER__USER__H

#include <string>

namespace server {

  /// class User - 
  class User {
    // Attributes
  public:
    int id;
    std::string name;
    // Operations
  public:
    User (int id, std::string name);
  };

};

#endif
