// Generated by dia2code
#ifndef SERVER__USERDB__H
#define SERVER__USERDB__H

#include <vector>

namespace server {
  class User;
  class endpoint;
  class net;
  class router;
  class http;
}

#include "endpoint.h"
#include "net.h"
#include "router.h"
#include "http.h"
#include "User.h"

namespace server {

  /// class UserDB - 
  class UserDB {
    // Associations
    // Attributes
  public:
    std::vector<User*> users;
    // Operations
  public:
    void getUser ( const Net::Rest::Request& request, Net::Http::ResponseWriter response);
    void removeUser ( const Net::Rest::Request& request, Net::Http::ResponseWriter response);
    void getAllUsers ( const Net::Rest::Request& request, Net::Http::ResponseWriter response);
    void addOrModUser ( const Net::Rest::Request& request, Net::Http::ResponseWriter response);
  };

};

#endif
