// Generated by dia2code
#ifndef SERVER__USER__C
#define SERVER__USER__C

#include "User.h"

namespace server {
  class UserDB;


}


namespace server {


    User::User(int id, std::string name) : name(name), id(id) {}

};

#endif
