// Generated by dia2code
#ifndef ENGINE__ACTIONTYPEID__H
#define ENGINE__ACTIONTYPEID__H


namespace engine {

  enum ActionTypeID {
    NODECHANGE     = 0,
    ACTIONCHANGE     = 1,
    SCREENCHANGE     = 2
  };

};

#endif
