// Generated by dia2code
#ifndef ENGINE__ACTION__H
#define ENGINE__ACTION__H

#include <string>

namespace state {
  class State;
  class Element;
};
namespace engine {
  class Command;
}

#include "Command.h"
#include "state/Element.h"

namespace engine {

  /// class Action - 
  class Action : public engine::Command {
    // Operations
  public:
    Action ();
    ~Action ( );
    void apply (state::State* state, state::Element* caster, int action, state::Element* target, bool notify);
    void Attack (state::Element* caster, state::Element* target);
    void SpellCast (int ability, state::Element* caster, state::Element* target);
    void TakeDamage (std::string damage, state::Element* target);
    void Heal (int heal, state::Element* target);
    void exec ();
    void UseItem (int id_item, state::Element* caster, state::Element* target);
  };

};

#endif
