// Generated by dia2code
#ifndef ENGINE__COMMAND__C
#define ENGINE__COMMAND__C


namespace engine {
  class MoveInUI;
  class Action;

}

#include "Command.h"

namespace engine {


    Command::Command() {

    }

    Command::~Command() {

    }

    state::State *Command::getState() {
        return this->state;
    }

    void Command::setState(state::State *state) {
        this->state = state;
    }

};

#endif
