// Generated by dia2code
#ifndef ENGINE__COMMAND__H
#define ENGINE__COMMAND__H


namespace state {
  class State;
}

#include "state/State.h"

namespace engine {

  /// class Command - 
  class Command {
    // Attributes
  protected:
    state::State* state;
    // Operations
  public:
    virtual void exec () = 0;
    Command ();
    ~Command ();
    state::State* getState ();
    void setState (state::State* state);
  };

};

#endif
