// Generated by dia2code
#ifndef ENGINE__ENGINE__H
#define ENGINE__ENGINE__H

#include <vector>

namespace engine {
  class Command;
};
namespace state {
  class Element;
};
namespace engine {
  class Rules;
}

#include "Command.h"
#include "Rules.h"

namespace engine {

  /// class Engine - 
  class Engine {
    // Associations
    // Attributes
  public:
    std::vector<Command> commands;
    state::Element* target;
    unsigned long targetIndex;
  protected:
    Rules* rules;
    // Operations
  public:
    void addCmd (Command* cmd);
    Engine ();
    ~Engine ();
    Rules* getRules ();
    void setRules (Rules* rules);
    void turnInit (state::Element* element);
  };

};

#endif
