

// Generated by dia2code
#ifndef ENGINE__ENGINE__C
#define ENGINE__ENGINE__C


namespace engine {
  class Rules;
  class Command;


}

#include "Engine.h"

namespace engine {
    void Engine::addCmd(Command* cmd) {
      //commands.push_back(*cmd);
    }

    Engine::Engine() {
    }

    Engine::~Engine() {

    }

    void Engine::turnInit(state::Element *element) {

      rules->getState()->currentTurn = element;
      rules->getState()->setPlayerFinishedTurn(false);
      if (!element->getIsCharacter())
      {
          //IA stuff here
      }
    }

    Rules* Engine::getRules() {
      return rules;
    }

    void Engine::setRules(Rules* rules) {
      this->rules = rules;
    }

};

#endif
