// Generated by dia2code
#ifndef ENGINE__MOVEINUI__H
#define ENGINE__MOVEINUI__H

#include <string>

namespace engine {
  class Command;
}

#include "Command.h"

namespace engine {

  /// class MoveInUI - 
  class MoveInUI : public engine::Command {
    // Operations
  public:
    void setChange (state::Node* tarnode);
    void setChange (std::string tarStr);
    void exec ();
    void setScreenChange (std::string nextscrn);
  };

};

#endif
