// Generated by dia2code
#ifndef ENGINE__MOVEINUI__C
#define ENGINE__MOVEINUI__C

#include "MoveInUI.h"

namespace engine {


    void MoveInUI::setNode(state::Node *tarnode) {
      state->setNode(tarnode);
    }

    void MoveInUI::setAction(std::string tarStr) {
      state->currentAction = tarStr;
    }

    void MoveInUI::exec() {
        switch(actionType){
            case ACTIONCHANGE:
                setAction(str);
                break;
            case NODECHANGE:
                setNode(node);
                break;
            case SCREENCHANGE:
                setScreenChange(str);
                break;
            default:
                break;
        }

    }

    void MoveInUI::setScreenChange(std::string nextscrn) {
      state->nextScreen = nextscrn;
      state->needScreenChange = true;
    }

    MoveInUI::MoveInUI(state::State *state, int actionType, state::Node *arg) : actionType(actionType),
                                                                                node(arg)
    {
        setState(state);
    }

    MoveInUI::MoveInUI(state::State *state, int actionType, std::string arg) : actionType(actionType),
                                                                               str(arg)
    {
        setState(state);
    }

};

#endif
