// Generated by dia2code
#ifndef ENGINE__MOVEINUI__C
#define ENGINE__MOVEINUI__C

#include "MoveInUI.h"

namespace engine {


    void MoveInUI::setChange(state::Node *tarnode) {
      state->setNode(tarnode);
    }

    void MoveInUI::setChange(std::string tarStr) {
      state->currentAction = tarStr;
    }

    void MoveInUI::exec() {

    }

    void MoveInUI::setScreenChange(std::string nextscrn) {
      state->nextScreen = nextscrn;
      state->needScreenChange = true;
    }

    MoveInUI::MoveInUI(state::State *state) {
        setState(state);
    }
};

#endif
