// Generated by dia2code
#ifndef ENGINE__MOVEINUI__H
#define ENGINE__MOVEINUI__H

#include <string>

namespace state {
  class State;
};
namespace engine {
  class Command;
}

#include "Command.h"
#include "ActionTypeID.h"

namespace engine {

  /// class MoveInUI - 
  class MoveInUI : public engine::Command {
    // Associations
    // Attributes
  public:
    int actionType;
    std::string str;
    state::Node* node;
    // Operations
  public:
    void setNode (state::Node* tarnode);
    void setAction (std::string tarStr);
    void exec ();
    void setScreenChange (std::string nextscrn);
    MoveInUI (state::State* state, int actionType, state::Node* arg);
    MoveInUI (state::State* state, int actionType, std::string arg);
  };

};

#endif
