// Generated by dia2code
#ifndef INSTANCE__RULES__C
#define INSTANCE__RULES__C

#include <iostream>
#include "Rules.h"
#include "../state/State.h"
#include "algorithm"


namespace engine {


    Rules::Rules() {

    }

    Rules::Rules(state::State *state, bool aichar, bool aimonster) {
        this->state = state;
        AICharNeeded = aichar;
        AIMonsterNeeded = aimonster;
    }

    Rules::~Rules() {

    }

    bool Rules::getAICharNeeded() {
        return AICharNeeded;
    }

    void Rules::setAICharNeeded(bool aicharneeded) {
        AICharNeeded = aicharneeded;
    }

    bool Rules::getAIMonsterNeeded() {
        return AIMonsterNeeded;
    }

    void Rules::setAIMonsterNeeded(bool aimonsterneeded) {
        AIMonsterNeeded = aimonsterneeded;
    }

    std::vector<state::Element *> Rules::getTurnList() {
        return TurnList;
    }

    void Rules::setTurnList(std::vector<state::Element *> turnlist) {
        TurnList = turnlist;
    }

    void Rules::init() {
        std::vector<int> tab_agi_element;
        int i,j;
        tab_agi_element.clear();
        TurnList.clear();

        for(i=0; i<state->getElementList()->element.size();++i){
            tab_agi_element.push_back(state->getElementList()->element[i]->getAgility());
            TurnList.push_back(state->getElementList()->element[i]);
        }

        i=0;j=1;
        while(i<state->getElementList()->element.size()-1){
            if(tab_agi_element[i]<tab_agi_element[j]){
                std::swap(tab_agi_element[i],tab_agi_element[j]);
                std::swap(TurnList[i], TurnList[j]);

            }
            ++j;
            if(j==state->getElementList()->element.size()){
                ++i;
                j=i+1;
            }
        }

        std::cout << std::to_string(TurnList.size()) << std::endl;

    }

    void Rules::NextTurn() {
        std::vector<state::Element*> TurnList = TurnList;
        state::Element* element_temp = TurnList.at(0);

        TurnList.erase(TurnList.begin());
        TurnList.push_back(element_temp);


        TurnList.swap(TurnList);

    }

    void Rules::setState(state::State *state) {
        this->state = state;
    }

    state::State *Rules::getState() {
        return state;
    }
};

#endif