// Generated by dia2code
#ifndef RENDER__ANIMATION__H
#define RENDER__ANIMATION__H


namespace render {
  class Element;
  class Surface;
}

namespace render {

  /// class Animation - 
  class Animation {
    // Attributes
  protected:
    int nbImage;
    int x;
    /// 	
    int y;
    Element* element;
    float speed;
    double start;
    // Operations
  public:
    Animation (int x, int y, Element* element);
    update (double time, Surface* surface);
  };

};

#endif
