// Generated by dia2code
#ifndef RENDER__CLAUDEUI__H
#define RENDER__CLAUDEUI__H

#include "SFML/Graphics.hpp"
#include "SFML/Audio.hpp"

namespace sf {
  class Text;
}


namespace render {

  /// class ClaudeUI - 
  class ClaudeUI {
    // Attributes
  protected:
    sf::Text abilities;
    sf::Text attack;
  };

};

#endif
