// Generated by dia2code
#ifndef RENDER__NODESPRITE__C
#define RENDER__NODESPRITE__C

#include "ElemSprite.h"

namespace sf {
  class Texture;
  class Sprite;
}


namespace render {


    ElemSprite::ElemSprite(sf::Texture *texture, float px, float py, std::string name, int id) : px(px),
                                                                                                 py(py),
                                                                                                 texture(texture),
                                                                                                 name(name),
                                                                                                 id(id){ }

    ElemSprite::~ElemSprite() {

    }

    float ElemSprite::getPositionY() {
        return py;
    }

    float ElemSprite::getPositionX() {
        return px;
    }

    int ElemSprite::getId() {
        return id;
    }

    std::string ElemSprite::getName() {
        return name;
    }
};

#endif
