// Generated by dia2code
#ifndef RENDER__ELEMENTLISTLAYER__H
#define RENDER__ELEMENTLISTLAYER__H


namespace state {
  class ElementList;
  class StateEvent;
};
namespace render {
  class Layer;
}

#include "Layer.h"
#include "state/ElementList.h"

namespace render {

  /// class ElementListLayer - 
  class ElementListLayer : public render::Layer, public state::ElementList {
    // Operations
  public:
    void update (state::ElementList* entitylist, int i);
    void stateChanged (state::StateEvent* etat);
  };

};

#endif
