// Generated by dia2code
#ifndef RENDER__ELEMENTRENDERSET__H
#define RENDER__ELEMENTRENDERSET__H


namespace render {
  class ElementRender;
}

#include "ElementRender.h"

namespace render {

  /// class ElementRenderSet - 
  class ElementRenderSet {
    // Associations
    // Operations
  public:
    ElementRenderSet ();
    ~ElementRenderSet ();
    const char* getImageFile ( );
  };

};

#endif
