// Generated by dia2code
#ifndef RENDER__ELEMENTLISTLAYER__H
#define RENDER__ELEMENTLISTLAYER__H


namespace render {
  class Layer;
}

#include "Layer.h"

namespace render {

  /// class ElementListLayer - 
  class ElementListLayer : public render::Layer {
    // Operations
  public:
    void update (state::ElementList* entitylist, int i);
    void stateChanged (state::StateEvent* etat);
  };

};

#endif
