// Generated by dia2code
#ifndef RENDER__ELEMSPRITE__H
#define RENDER__ELEMSPRITE__H

#include "SFML/Graphics.hpp"
#include "SFML/Audio.hpp"
#include <string>

namespace sf {
  class Texture;
  class Sprite;
}


namespace render {

  /// class ElemSprite - 
  class ElemSprite : public sf::Sprite {
    // Attributes
  public:
    sf::Texture* texture;
  protected:
    float py;
    float px;
    std::string name;
    int id;
    // Operations
  public:
    ElemSprite (sf::Texture* texture, float px, float py, std::string name, int id);
    ~ElemSprite ();
    float getPositionY ();
    float getPositionX ();
    int getId ();
    std::string getName ();
  };

};

#endif
