// Generated by dia2code
#ifndef RENDER__ELEMENT__H
#define RENDER__ELEMENT__H

#include <vector>

namespace render {
  class Element;
}

namespace render {

  /// class Element - 
  class Element {
    // Attributes
  protected:
    std::vector<const Element*> element ;
    int x;
    int y;
    int w;
    /// 	
    int h;
    float rate;
    bool isAnimated;
    // Operations
  public:
    Element ();
    ~Element ();
  };

};

#endif
