// Generated by dia2code
#ifndef RENDER__ELEMENTRENDERSET__C
#define RENDER__ELEMENTRENDERSET__C


namespace render {
    class ElementRender;
}

#include "ElementRenderSet.h"

namespace render {

}

#endif