// Generated by dia2code
#ifndef RENDER__NODESPRITE__C
#define RENDER__NODESPRITE__C

#include "ElemSprite.h"

namespace sf {
  class Texture;
  class Sprite;
}


namespace render {


    ElemSprite::ElemSprite(state::Element* element, sf::Texture *texture, float px, float py, std::string name, int id) : px(px),
                                                                                                 py(py),
                                                                                                 element(element),
                                                                                                 texture(texture),
                                                                                                 name(name),
                                                                                                 id(id){ }

    ElemSprite::ElemSprite(state::Node *node, sf::Texture *texture, float px, float py, std::string name, int id) : px(px),
                                                                                                                    py(py),
                                                                                                                    node(node),
                                                                                                                    texture(texture),
                                                                                                                    name(name),
                                                                                                                    id(id){ }

    ElemSprite::~ElemSprite() {

    }

    float ElemSprite::getPositionY() {
        return py;
    }

    float ElemSprite::getPositionX() {
        return px;
    }

    int ElemSprite::getId() {
        return id;
    }

    std::string ElemSprite::getName() {
        return name;
    }

    void ElemSprite::setPositionX(float x) {
        px = x;
    }

    void ElemSprite::setPositionY(float y) {
        py = y;
    }

};

#endif
