// Generated by dia2code
#ifndef RENDER__ELEMENTRENDER__H
#define RENDER__ELEMENTRENDER__H

#include <vector>

namespace render {
  class ElementRender;
}

namespace render {

  /// class ElementRender - 
  class ElementRender {
    // Attributes
  protected:
    std::vector<const ElementRender*> elementrender;
    int x;
    int y;
    int w;
    /// 	
    int h;
    float rate;
    bool isAnimated;
    // Operations
  public:
    ElementRender ();
    ~ElementRender ();
    std::vector<ElementRender*> getElementRender ();
    void setElementRender (std::vector<ElementRender*> elementrender);
    int getX ();
    void setX (int x);
    int getY ();
    void setY (int y);
    int getW ();
    void setW (int w);
    int getH ();
    void setH (int h);
    float getRate ();
    void setRate (float rate);
    bool getIsAnimated ();
    void setIsAnimated (bool isAnimated);
  };

};

#endif
