// Generated by dia2code
#ifndef RENDER__FIGHTRENDERER__C
#define RENDER__FIGHTRENDERER__C

#include "FightRenderer.h"

namespace render {
  class Renderer;
  class YouennUI;
  class ClaudeUI;

}


namespace render {

    FightRenderer::FightRenderer(sf::Font *font, sf::RenderWindow *window) : Renderer(font, window)
    {
        background.loadFromFile("../res/fightbackground.jpg");
        setBackground();
    }

    FightRenderer::~FightRenderer() {

    }

    void FightRenderer::render()
    {
        window->draw(spriteScreen);
    }

    void FightRenderer::setBackground() {
        spriteScreen.setTexture(background);

        spriteScreen.setOrigin((int)background.getSize().x/2, (int)background.getSize().y/2);
        spriteScreen.move(400, 300);
    }

};

#endif
