// Generated by dia2code
#ifndef RENDER__FIGHTRENDERER__H
#define RENDER__FIGHTRENDERER__H

#include "SFML/Graphics.hpp"
#include "SFML/Audio.hpp"

namespace render {
  class Renderer;
  class YouennUI;
  class ClaudeUI;
}

#include "Renderer.h"
#include "YouennUI.h"
#include "ClaudeUI.h"

namespace render {

  /// class FightRenderer - 
  class FightRenderer : public render::Renderer {
    // Operations
  public:
    FightRenderer (sf::Font* font, sf::RenderWindow* window);
    virtual ~FightRenderer ();
    void render ();
    void setBackground ();
    void initRender ();
  };

};

#endif
