// Generated by dia2code
#ifndef RENDER__FIGHTUI__C
#define RENDER__FIGHTUI__C

#include "FightUI.h"
namespace sf {
    class Text;
}


namespace render {


        sf::Text FightUI::getMp ()
        {
            return mp;
        }
        sf::Text FightUI::getHp ()
        {
            return this->hp;
        }
        void FightUI::setMp (sf::Text mp)
        {
            this->mp = mp;
        }
        void FightUI::setHp (sf::Text hp)
        {
            this->hp = hp;
        }
        void FightUI::setAb (sf::Text ab)
        {
            this->abilities = ab;
        }
        void FightUI::setAtt (sf::Text att)
        {
            this->attack = att;
        }
        sf::Text FightUI::getAb ()
        {
            return abilities;
        }
        sf::Text FightUI::getAtt ()
        {
            return attack;
        }
        void FightUI::display ()
        {
            //window->draw(hp);
        }
    FightUI::~FightUI ()
        {

        }
    FightUI::FightUI (sf::RenderWindow* window)
        {
            this->window = window;
            sf::Font font;
            font.loadFromFile("../res/Square.ttf");
            hp.setFont(font);
            hp.setPosition(400, 400);
            hp.setString("test");
        }




};

#endif

