// Generated by dia2code
#ifndef RENDER__FIGHTUI__H
#define RENDER__FIGHTUI__H

#include "SFML/Graphics.hpp"
#include "SFML/Audio.hpp"

namespace sf {
  class Text;
}


namespace render {

  /// class FightUI - 
  class FightUI {
    // Attributes
  protected:
    sf::Text abilities;
    sf::Text attack;
    sf::Text hp;
    sf::Text mp;
    sf::RenderWindow* window;
    // Operations
  public:
    sf::Text getMp ();
    sf::Text getHp ();
    void setMp (sf::Text mp);
    void setHp (sf::Text hp);
    void setAb (sf::Text ab);
    void setAtt (sf::Text att);
    sf::Text getAb ();
    sf::Text getAtt ();
    void display ();
    ~FightUI ();
    FightUI (sf::RenderWindow* window);
  };

};

#endif
