// Generated by dia2code
#ifndef RENDER__FIGHTRENDERER__H
#define RENDER__FIGHTRENDERER__H

#include "SFML/Graphics.hpp"
#include "SFML/Audio.hpp"
#include <vector>

namespace sf {
  class Sprite;
  class Text;
  class Texture;
};
namespace render {
  class Renderer;
};
namespace instance {
  class Fight;
}

#include "Renderer.h"
#include "instance/Fight.h"

namespace render {

  /// class FightRenderer - 
  class FightRenderer : public render::Renderer {
    // Associations
    // Attributes
  public:
    std::vector<sf::Sprite*> spriteList;
    std::vector<sf::Text> hpTexts;
    sf::Text turnText;
    // Operations
  public:
    FightRenderer (sf::RenderWindow* window);
    virtual ~FightRenderer ();
    void render ();
    void setBackground ();
    void initRender ();
    void initElemSprite (float px, float py, sf::Texture* text, sf::Sprite* sprite);
  };

};

#endif
