// Generated by dia2code
#ifndef RENDER__INNRENDERER__H
#define RENDER__INNRENDERER__H

#include "SFML/Graphics.hpp"
#include "SFML/Audio.hpp"

namespace render {
  class Renderer;
}

#include "Renderer.h"

namespace render {

  /// class InnRenderer - 
  class InnRenderer : public render::Renderer {
    // Operations
  public:
    InnRenderer (sf::Font* font, sf::RenderWindow* rwindow);
    ~InnRenderer ();
    void render ();
    void setBackground ();
    void initRender ();
  };

};

#endif
