// Generated by dia2code
#ifndef RENDER__INTRORENDERER__H
#define RENDER__INTRORENDERER__H

#include "SFML/Graphics.hpp"
#include "SFML/Audio.hpp"

namespace sf {
  class Text;
};
namespace render {
  class Renderer;
};
namespace instance {
  class Intro;
}

#include "Renderer.h"
#include "instance/Intro.h"

namespace render {

  /// class IntroRenderer - 
  class IntroRenderer : public render::Renderer {
    // Associations
    // Attributes
  protected:
    sf::Text pressAnyKey;
    sf::Text title;
    // Operations
  public:
    void render ();
    void setBackground ();
    IntroRenderer (sf::RenderWindow* rwindow);
    ~IntroRenderer ();
    void initRender ();
  };

};

#endif
