// Generated by dia2code
#ifndef RENDER__INTRORENDERER__C
#define RENDER__INTRORENDERER__C

#include "IntroRenderer.h"

namespace sf {
  class Text;
};
namespace render {
  class Renderer;

    IntroRenderer::IntroRenderer(sf::Font *font, sf::RenderWindow *rwindow,) {
        background.loadFromFile("../res/introbackground.png");
        setBackground();
    }

    IntroRenderer::~IntroRenderer() {

    }

    void IntroRenderer::render() {
        //Draw all elements of the Intro screen here, the last drawn element will appear on top

        window->draw(spriteScreen);
        window->draw(title);
        window->draw(pressAnyKey);
    }

    void IntroRenderer::setBackground() {
        spriteScreen.setTexture(background);

        spriteScreen.setOrigin((int)background.getSize().x/2, (int)background.getSize().y/2);
        spriteScreen.move(400, 300);
    }

    void IntroRenderer::initRender() {

        title.setFont(*font);
        title.setCharacterSize(80);
        title.setString("Final fantastique");
        title.setPosition({ 400, 150 });
        title.setOrigin(title.getLocalBounds().width/2, title.getLocalBounds().height/2);


        pressAnyKey.setFont(*font);
        pressAnyKey.setCharacterSize(20);
        pressAnyKey.setString("Press any key");
        pressAnyKey.setPosition({ 400, 450 });
        pressAnyKey.setOrigin(pressAnyKey.getLocalBounds().width/2, pressAnyKey.getLocalBounds().height/2);

    }
}

#include "Renderer.h"

namespace render {


};

#endif
