// Generated by dia2code
#ifndef RENDER__LAYER__H
#define RENDER__LAYER__H

#include <map>

namespace render {
  class Surface;
  class ElementRenderSet;
  class Animation;
}

#include "Animation.h"
#include "ElementRenderSet.h"
#include "Surface.h"

namespace render {

  /// class Layer - 
  class Layer {
    // Associations
    // Attributes
  protected:
    std::map<int, Animation*> animations;
    Surface* surface;
    ElementRenderSet* elementRenderSet;
    // Operations
  public:
    Layer ();
    ~Layer ();
    void printText (int x, int y, const char* msg, int w, int h);
    void update (double time);
    std::map<int,Animation*> getAnimations ();
    void setAnimations (std::map<int,Animation*> animations);
    Surface* getSurface ();
    void setSurface (Surface* surface);
    ElementRenderSet* getElementRenderSet ();
    void setElementRenderSet (ElementRenderSet* elementrenderset);
  };

};

#endif
