// Generated by dia2code
#ifndef RENDER__LAYER__H
#define RENDER__LAYER__H

#include <map>

namespace render {
  class Surface;
  class ElementSet;
}

namespace render {

  /// class Layer - 
  class Layer {
    // Attributes
  protected:
    std::map<int, Animation*> animations;
    Surface* surface;
    ElementSet* elementSet;
    // Operations
  public:
    Layer ();
    ~Layer ();
    printText (int x, int y, const char* msg, int w, int h);
    update (double time);
  };

};

#endif
