// Generated by dia2code
#ifndef RENDER__NODESPRITE__C
#define RENDER__NODESPRITE__C

#include "NodeSprite.h"

namespace sf {
  class Texture;
  class Sprite;
}


namespace render {


    NodeSprite::NodeSprite(sf::Texture *texture, float px, float py, std::string name, int id) : px(px),
                                                                                                 py(py),
                                                                                                 texture(texture),
                                                                                                 name(name),
                                                                                                 id(id){ }

    NodeSprite::~NodeSprite() {

    }

    float NodeSprite::getPositionY() {
        return py;
    }

    float NodeSprite::getPositionX() {
        return px;
    }

    int NodeSprite::getId() {
        return id;
    }

    std::string NodeSprite::getName() {
        return name;
    }
};

#endif
