// Generated by dia2code
#ifndef RENDER__NODESPRITE__H
#define RENDER__NODESPRITE__H

#include "SFML/Graphics.hpp"
#include "SFML/Audio.hpp"
#include <string>

namespace sf {
  class Texture;
  class Sprite;
}


namespace render {

  /// class NodeSprite - 
  class NodeSprite : public sf::Sprite {
    // Attributes
  protected:
    float py;
    float px;
    std::string name;
    int id;
    // Operations
  public:
    sf::Texture* texture;
    NodeSprite (sf::Texture* texture, float px, float py, std::string name, int id);
    ~NodeSprite ();
    float getPositionY ();
    float getPositionX ();
    int getId ();
    std::string getName ();
  };

};

#endif
