// Generated by dia2code
#ifndef RENDER__RENDERER__C
#define RENDER__RENDERER__C

#include "Renderer.h"

namespace sf {
  class Texture;
  class Sprite;
};
namespace state {
  class State;
};
namespace render {
  class TextureSetter;

    Renderer::Renderer(sf::RenderWindow* rwindow) {
        window = rwindow;
    }

    Renderer::~Renderer() {

    }

    void Renderer::setFont(sf::Font font) {
        this->font = font;
    }
}

#include "TextureSetter.h"
#include "state/State.h"

namespace render {



};

#endif
