// Generated by dia2code
#ifndef RENDER__RENDERER__C
#define RENDER__RENDERER__C

#include "Renderer.h"

namespace sf {
  class Texture;
  class Sprite;
};
namespace state {
  class State;
};
namespace render {
  class TextureSetter;
}

#include "TextureSetter.h"
#include "state/State.h"

namespace render {



};

#endif
