// Generated by dia2code
#ifndef RENDER__RENDERER__H
#define RENDER__RENDERER__H

#include "SFML/Graphics.hpp"
#include "SFML/Audio.hpp"

namespace sf {
  class Texture;
  class Sprite;
};
namespace state {
  class State;
};
namespace render {
  class TextureSetter;
};
namespace instance {
  class Screen;
}

#include "state/State.h"
#include "instance/Screen.h"
#include "TextureSetter.h"

namespace render {

  /// class Renderer - Wrapper screen rendering
  class Renderer {
    // Associations
    // Attributes
  protected:
    sf::Texture background;
    sf::Font font;
    sf::RenderWindow* window;
    sf::Sprite spriteScreen;
    state::State* state;
    TextureSetter* texturesetter;
    // Operations
  public:
    Renderer (sf::RenderWindow* rwindow);
    virtual ~Renderer ();
    virtual void render () = 0;
    virtual void setBackground () = 0;
    virtual void initRender () = 0;
    void setFont (sf::Font font);
  };

};

#endif
