// Generated by dia2code
#ifndef RENDER__SCENELAYER__H
#define RENDER__SCENELAYER__H


namespace render {
  class Scene;
}

#include "Scene.h"

namespace render {

  enum SceneLayer {
    BackGround_Layer     = 0,
    Character_Layer     = 1,
    Data_Character_Layer     = 2,
    State_Layer     = 3
  };

};

#endif
