// Generated by dia2code
#ifndef RENDER__SCENE__H
#define RENDER__SCENE__H

#include <vector>

namespace render {
  class Layer;
  class Surface;
}

namespace render {

  /// class Scene - 
  class Scene {
    // Attributes
  public:
    std::vector<Layer*> layers;
  protected:
    int w;
    int h;
    // Operations
  public:
    Scene ();
    ~Scene ();
    update (double time);
    registerObservers (state::State* etat);
    unregisterObservers (state::State* etat);
    stateChanged (state::StateEvent* event);
    int getLayerCount ();
    setLayer (int id, Layer* layer);
    setSurface (int id, Surface* surface);
  };

};

#endif
