// Generated by dia2code
#ifndef RENDER__SCENE__H
#define RENDER__SCENE__H

#include <vector>

namespace render {
  class Layer;
};
namespace state {
  class StateEvent;
};
namespace render {
  class Surface;
  class StateLayer;
  class ElementListLayer;
}

#include "state/StateEvent.h"
#include "StateLayer.h"
#include "ElementListLayer.h"

namespace render {

  /// class Scene - 
  class Scene : public state::StateEvent {
    // Associations
    // Attributes
  protected:
    std::vector<Layer*> layers;
    int w;
    int h;
    // Operations
  public:
    Scene ();
    ~Scene ();
    void update (double time);
    void registerObservers (state::State* etat);
    void unregisterObservers (state::State* etat);
    void stateChanged (state::StateEvent* event);
    int getLayerCount ();
    void setLayer (int id, Layer* layer);
    void setSurface (int id, Surface* surface);
  };

};

#endif
