// Generated by dia2code
#ifndef RENDER__STATELAYER__H
#define RENDER__STATELAYER__H


namespace render {
  class Layer;
}

#include "Layer.h"
#include "../state.h"

namespace render {

  /// class StateLayer - 
  class StateLayer : public render::Layer {
    // Operations
  public:
    void stateChanged (state::StateEvent* etat);
  };

};

#endif
