// Generated by dia2code
#ifndef RENDER__SURFACE__H
#define RENDER__SURFACE__H


namespace render {

  /// class Surface - 
  class Surface {
    // Attributes
  protected:
    int IDsurface;
    // Operations
  public:
    Surface ();
    ~Surface ();
    void loadTexture (int IDsurface);
    void clear ();
    int getIDSurface ();
    void setIDSurface (int idsurface);
  };

};

#endif
