// Generated by dia2code
#ifndef RENDER__SURFACEID__H
#define RENDER__SURFACEID__H


namespace render {

  enum SurfaceID {
    Town1_Surface      = 0,
    Town2_Surface     = 1,
    Town3_Surface     = 2,
    Forest     = 3,
    Cave     = 4,
    Grassland     = 5,
    Tavern     = 6
  };

};

#endif
