// Generated by dia2code
#ifndef RENDER__TEXTURESETTER__C
#define RENDER__TEXTURESETTER__C

#include "TextureSetter.h"
#include <map>
#include <iostream>

namespace sf {
  class Texture;
};
namespace state {
  class State;
}

#include "state/State.h"

namespace render {


    TextureSetter::TextureSetter() {
        nodeTextureMap.insert(std::pair<std::string, sf::Texture*>("0_Midgare_150_450", new sf::Texture));
        nodeTextureMap.insert(std::pair<std::string, sf::Texture*>("1_Nibelheim_250_350", new sf::Texture));
        nodeTextureMap.insert(std::pair<std::string, sf::Texture*>("2_Besaid_100_150", new sf::Texture));
        nodeTextureMap.insert(std::pair<std::string, sf::Texture*>("3_Gagazet_300_200", new sf::Texture));
        nodeTextureMap.insert(std::pair<std::string, sf::Texture*>("4_Winhill_550_280", new sf::Texture));
        nodeTextureMap.insert(std::pair<std::string, sf::Texture*>("5_Terra_650_350", new sf::Texture));
        nodeTextureMap.insert(std::pair<std::string, sf::Texture*>("6_Kilika_750_325", new sf::Texture));
        nodeTextureMap.insert(std::pair<std::string, sf::Texture*>("7_Lindblum_700_200", new sf::Texture));
        nodeTextureMap.insert(std::pair<std::string, sf::Texture*>("8_Zanarkand_350_50", new sf::Texture));

        for(auto i : nodeTextureMap)
        {
            i.second->loadFromFile("../res/red_circle.png");

        }

        sf::Texture* tTemp = new sf::Texture;
        elementTextureMap.insert(std::pair<std::string, sf::Texture*>("0_Claude_150_450", tTemp));
        tTemp->loadFromFile("../res/Claude_64x64/Claude014.png");
        //elementTextureMap.insert(std::pair<std::string, sf::Texture*>("1_Youenn_0_0", new sf::Texture));
        //Add rest of monsters etc
    }

    TextureSetter::~TextureSetter() {

    }

    sf::Texture TextureSetter::getTexture(state::ElementList* eList) {

        return sf::Texture();
    }
};

#endif
