// Generated by dia2code
#ifndef RENDER__TEXTURESETTER__H
#define RENDER__TEXTURESETTER__H

#include "SFML/Graphics.hpp"
#include "SFML/Audio.hpp"
#include <string>
#include <map>

namespace sf {
  class Texture;
};
namespace state {
  class State;
}

#include "state/State.h"

namespace render {

  /// class TextureSetter - 
  class TextureSetter {
    // Attributes
  public:
    std::map<std::string, sf::Texture*> nodeTextureMap;
    std::map<int, sf::Texture*> elementTextureMap;
    // Operations
  public:
    TextureSetter ();
    ~TextureSetter ();
    sf::Texture getTexture (state::ElementList* eList);
  };

};

#endif
