// Generated by dia2code
#ifndef RENDER__WORLDMAPRENDERER__H
#define RENDER__WORLDMAPRENDERER__H

#include "SFML/Graphics.hpp"
#include "SFML/Audio.hpp"
#include <vector>

namespace render {
  class ElemSprite;
};
namespace sf {
  class Text;
};
namespace render {
  class Renderer;
};
namespace instance {
  class Worldmap;
}

#include "Renderer.h"
#include "instance/Worldmap.h"
#include "ElemSprite.h"

namespace render {

  /// class WorldmapRenderer - 
  class WorldmapRenderer : public render::Renderer {
    // Associations
    // Attributes
  public:
    render::ElemSprite* charSprite;
  protected:
    sf::Text tmap;
    std::vector<render::ElemSprite*> tabNodeSprite;
    // Operations
  public:
    WorldmapRenderer (sf::RenderWindow* rwindow);
    ~WorldmapRenderer ();
    void render ();
    void renderNodes (std::vector<render::ElemSprite*> tabNode);
    void setBackground ();
    void initRender ();
    void renderNodeChange (render::ElemSprite* n1, render::ElemSprite* n2);
  };

};

#endif
