// Generated by dia2code
#ifndef RENDER__WORLDMAPRENDERER__H
#define RENDER__WORLDMAPRENDERER__H

#include "SFML/Graphics.hpp"
#include "SFML/Audio.hpp"
#include <vector>

namespace sf {
  class Text;
};
namespace render {
  class NodeSprite;
  class Renderer;
};
namespace instance {
  class Worldmap;
}

#include "Renderer.h"
#include "instance/Worldmap.h"
#include "NodeSprite.h"

namespace render {

  /// class WorldmapRenderer - 
  class WorldmapRenderer : public render::Renderer {
    // Associations
    // Attributes
  protected:
    sf::Text tmap;
    std::vector<render::NodeSprite*> tabNodeSprite;
    // Operations
  public:
    WorldmapRenderer (sf::RenderWindow* rwindow);
    ~WorldmapRenderer ();
    void render ();
    void renderNodes (std::vector<render::NodeSprite*> tabNode);
    void setBackground ();
    void initRender ();
  };

};

#endif
