// Generated by dia2code
#ifndef AI__AI__C
#define AI__AI__C

#include "AI.h"




    ai::AI::AI() {

    }

    ai::AI::~AI() {

    }

    ai::AI::AI(instance::Fight *fight) {
        this->fight = fight;
        Notify = false;
    }

    instance::Fight *ai::AI::getFight() {
        return fight;
    }

    void ai::AI::setFight(instance::Fight *fight) {
        this->fight = fight;
    }

    int ai::AI::getChoiceAction() {
        return ChoiceAction;
    }

    void ai::AI::setChoiceAction(int choiceaction) {
        this->ChoiceAction = choiceaction;
    }

    int ai::AI::getId() {
        return Id;
    }

    bool ai::AI::getNotify() {
        return Notify;
    }

    void ai::AI::setNotify(bool notify) {
        Notify = notify;
    }


#endif


