// Generated by dia2code
#ifndef AI__AI__H
#define AI__AI__H


namespace instance {
  class Fight;
};
namespace state {
  class Element;
};
namespace ai {
  class ChoiceList;
};
namespace engine {
  class Engine;
}

#include "engine/Engine.h"
#include "ChoiceList.h"
#include "instance/Fight.h"

namespace ai {

  /// class AI - 
  class AI {
    // Associations
    // Attributes
  protected:
    instance::Fight* fight;
    int ChoiceAction;
    int Id;
    bool Notify;
    state::Element* ChoiceTarget;
    ChoiceList* choiceList;
    // Operations
  public:
    AI ();
    ~AI ();
    AI (instance::Fight* fight);
    instance::Fight* getFight ();
    void setFight (instance::Fight* fight);
    int getChoiceAction ();
    void setChoiceAction (int choiceaction);
    int getId ();
    bool getNotify ();
    void setNotify (bool notify);
    virtual void run () = 0;
  };

};

#endif
