// Generated by dia2code
#ifndef AI__CHOICELIST__H
#define AI__CHOICELIST__H

#include <vector>

namespace state {
  class Element;
};
namespace instance {
  class Fight;
}

#include "state/Element.h"

namespace ai {

  /// class ChoiceList - 
  class ChoiceList {
    // Attributes
  protected:
    std::vector<int> allAction;
    std::vector<state::Element*> allyTarget;
    std::vector<state::Element*> ennemyTarget;
    // Operations
  public:
    ChoiceList ();
    ~ChoiceList ();
    ChoiceList (instance::Fight* fight);
    std::multimap<int,state::Element*> getRandomChoicePossibilities ();
    std::multimap<int,state::Element*> getRandomGoodChoicePossibilities ();
  };

};

#endif
