// Generated by dia2code
#ifndef AI__RANDOMCHOICE__H
#define AI__RANDOMCHOICE__H


namespace engine {
  class Engine;
};
namespace ai {
  class AI;
}

#include "AI.h"

namespace ai {

  /// class RandomChoice - 
  class RandomChoice : public ai::AI {
    // Operations
  public:
    RandomChoice ();
    ~RandomChoice ();
    void run ();
    RandomChoice (engine::Engine* engine);
  };

};

#endif
