// Generated by dia2code
#ifndef AI__RANDOMGOODCHOICE__H
#define AI__RANDOMGOODCHOICE__H


namespace engine {
  class Engine;
};
namespace ai {
  class AI;
}

#include "AI.h"

namespace ai {

  /// class RandomGoodChoice - 
  class RandomGoodChoice : public ai::AI {
    // Operations
  public:
    RandomGoodChoice ();
    ~RandomGoodChoice ();
    RandomGoodChoice (engine::Engine* engine);
    void run ();
  };

};

#endif
