// Generated by dia2code
#ifndef AI__RANDOMGOODCHOICE__H
#define AI__RANDOMGOODCHOICE__H


namespace engine {
  class Engine;
};
namespace instance {
  class Fight;
};
namespace ai {
  class AI;
}

#include "AI.h"

namespace ai {

  /// class RandomGoodChoice - 
  class RandomGoodChoice : public ai::AI {
    // Attributes
  public:
    engine::Engine* engine;
    // Operations
  public:
    RandomGoodChoice ();
    ~RandomGoodChoice ();
    RandomGoodChoice (instance::Fight* fight, engine::Engine* engine);
    void run ();
  };

};

#endif
