// Generated by dia2code
#ifndef AI__RANDOMGOODCHOICE__H
#define AI__RANDOMGOODCHOICE__H


namespace instance {
  class Fight;
};
namespace ai {
  class AI;
}

#include "AI.h"

namespace ai {

  /// class RandomGoodChoice - 
  class RandomGoodChoice : public ai::AI {
    // Operations
  public:
    RandomGoodChoice ();
    ~RandomGoodChoice ();
    RandomGoodChoice (instance::Fight* fight);
    void run ();
  };

};

#endif
