// Generated by dia2code
#ifndef AI__SMARTCHOICE__H
#define AI__SMARTCHOICE__H

#include <map>

namespace engine {
  class Engine;
};
namespace instance {
  class Fight;
};
namespace ai {
  class AI;
}

#include "AI.h"

namespace ai {

  /// class SmartChoice - 
  class SmartChoice : public ai::AI {
    // Attributes
  public:
    engine::Engine* engine;
    // Operations
  public:
    SmartChoice ();
    ~SmartChoice ();
    SmartChoice (instance::Fight* fight, engine::Engine* engine);
    void run ();
    std::map<int,float> minmax (engine::Engine* engine, bool minormax, int step);
  };

};

#endif
