// Generated by dia2code
#ifndef AI__SMARTCHOICE__H
#define AI__SMARTCHOICE__H

#include <map>

namespace engine {
  class Engine;
};
namespace ai {
  class AI;
}

#include "AI.h"

namespace ai {

  /// class SmartChoice - 
  class SmartChoice : public ai::AI {
    // Operations
  public:
    SmartChoice ();
    ~SmartChoice ();
    SmartChoice (engine::Engine* engine);
    void run ();
    std::map<int,float> minmax (engine::Engine* engine, bool minormax, int step);
  };

};

#endif
