// Generated by dia2code
#ifndef INSTANCE__ACTION__H
#define INSTANCE__ACTION__H

#include <string>

namespace state {
  class State;
  class Element;
}

#include "state/Element.h"

namespace instance {

  /// class Action - 
  class Action {
    // Operations
  public:
    Action ();
    ~Action ( );
    void apply (state::State* state, state::Element* caster, int action, state::Element* target, bool notify);
    void Attack (state::Element* caster, state::Element* target);
    void SpellCast (int ability, state::Element* caster, state::Element* target);
    void TakeDamage (std::string damage, state::Element* target);
    void Heal (int heal, state::Element* target);
  };

};

#endif
