// Generated by dia2code
#ifndef INSTANCE__APPLICATION__H
#define INSTANCE__APPLICATION__H
#define WINDOW_X 1600
#define WINDOW_Y 900

namespace instance {
  class Intro;
  class Worldmap;
  class Fight;
  class Inn;
};
namespace sf {
  class RenderWindow;
};
namespace instance {
  class Screen;
}

#include "Intro.h"
#include "Worldmap.h"
#include "Fight.h"
#include "Inn.h"
#include "SFML/Graphics.hpp"
#include "Screen.h"
#include <iostream>

namespace instance {

  /// class Application - RenderWindow used for display
  class Application : public sf::RenderWindow {
    // Attributes
  protected:
    sf::Font font;
    Intro intro;
    Worldmap worldmap;
    Fight fight;
    Inn inn;
    // Operations
  public:
    void play ();
    ~Application ();
    Application ();
  };

};

#endif
