// Generated by dia2code
#ifndef RENDER__FIGHTUI__C
#define RENDER__FIGHTUI__C

#include <instance/FightUI.h>
#include <iostream>
#include "FightUI.h"
namespace sf {
    class Text;
}


namespace instance {



    FightUI::~FightUI ()
        {

        }
    FightUI::FightUI (sf::RenderWindow* window)
        {
            idstr = "FightUI";
            this->window = window;
            font.loadFromFile("res/Square.ttf");

            attack.setString("attack");
            attack.setPosition(100, 100);
            attack.setColor(sf::Color::Red);
            attack.setFont(font);
            abilities.setString("abilities");
            abilities.setPosition(600, 100);
            abilities.setFont(font);
            overdrive.setString("overdrive");
            overdrive.setPosition(100, 150);
            overdrive.setFont(font);
            item.setString("item");
            item.setPosition(600, 150);
            item.setFont(font);


        }

    void FightUI::display() {

        window->draw(attack);
        window->draw(abilities);
        window->draw(overdrive);
        window->draw(item);

    }

    void FightUI::menuItemSwitch(sf::Text &t1, sf::Text &t2) {
        t1.setColor(sf::Color::White);
        t2.setColor(sf::Color::Red);
    }


};

#endif


