// Generated by dia2code
#ifndef INSTANCE__FIGHTUI__H
#define INSTANCE__FIGHTUI__H

#include "SFML/Graphics.hpp"
#include "SFML/Audio.hpp"

namespace sf {
  class RenderWindow;
};
namespace instance {
  class UI;
}

#include "UI.h"

namespace instance {

  /// class FightUI - 
  class FightUI : public instance::UI {
    // Attributes
  public:
    sf::Text abilities;
    sf::Text attack;
    sf::Text overdrive;
    sf::Text item;
  protected:
    sf::RenderWindow* window;
    // Operations
  public:
    void display ();
    ~FightUI ();
    FightUI (sf::RenderWindow* window);
    void menuItemSwitch (sf::Text& t1, sf::Text& t2);
  };

};

#endif
