// Generated by dia2code
#ifndef INSTANCE__FIGHT__C
#define INSTANCE__FIGHT__C


namespace sf {
  class RenderWindow;
};
namespace instance {
  class Screen;
}

#include "Fight.h"

namespace instance {

    Fight::Fight(sf::Font* f, sf::RenderWindow* w) : Screen(f,w) {
        background.loadFromFile("../res/fightbackground.jpg");
        setBackground();
    }

    void Fight::init() {
        //Init node logic
    }

    void Fight::render() {
        window->draw(spriteScreen);
    }

    Fight::~Fight() {}

    void Fight::eventHandler() {

    }

};

#endif
