// Generated by dia2code
#ifndef INSTANCE__FIGHT__H
#define INSTANCE__FIGHT__H

#include "render/FightRenderer.h"
#include <string>
#include "SFML/Graphics.hpp"
#include "SFML/Audio.hpp"

namespace render {
  class FightRenderer;
};
namespace state {
  class State;
};
namespace sf {
  class RenderWindow;
};
namespace instance {
  class Screen;
}

#include "Screen.h"
#include "render/FightRenderer.h"

namespace instance {

  /// class Fight - Handles fights rendering and logic
  class Fight : public instance::Screen {
    // Associations
    // Attributes
  public:
    render::FightRenderer* renderer;
  protected:
    std::string currentAction;
    state::State* state;
    // Operations
  public:
    Fight (sf::RenderWindow* window, render::FightRenderer* renderer, state::State* state);
    virtual ~Fight ();
    void init ();
    void eventHandler ();
  };

};

#endif
