// Generated by dia2code
#ifndef INSTANCE__INN__C
#define INSTANCE__INN__C


namespace sf {
  class RenderWindow;
};
namespace instance {
  class Screen;
}

#include "Inn.h"

namespace instance {

    Inn::Inn(sf::Font* f, sf::RenderWindow* w) : Screen(f,w) {
        background.loadFromFile("../res/innbackground.jpg");
        setBackground();
    }

    void Inn::init() {
        //Init node logic
    }

    void Inn::render() {
        window->draw(spriteScreen);
    }

    Inn::~Inn() {}

    void Inn::eventHandler() {

    }

};

#endif
