// Generated by dia2code
#ifndef INSTANCE__INN__C
#define INSTANCE__INN__C


namespace sf {
  class RenderWindow;
};
namespace instance {
  class Screen;
}

#include "Inn.h"

namespace instance {

    Inn::Inn(sf::RenderWindow* w, render::Renderer* rd) : Screen(w, rd) {

    }

    void Inn::init() {
        //Init node logic
    }

    Inn::~Inn() {}

    void Inn::eventHandler() {

    }

};

#endif
