// Generated by dia2code
#ifndef INSTANCE__INTRO__H
#define INSTANCE__INTRO__H

#include "SFML/Graphics.hpp"
#include "SFML/Audio.hpp"

namespace sf {
  class RenderWindow;
};
namespace instance {
  class Screen;
}

#include "Screen.h"

namespace instance {

  /// class Intro - Landing screen menu
  class Intro : public instance::Screen {
    // Operations
  public:
    Intro (sf::RenderWindow* window);
    virtual ~Intro ();
    void init ();
    void eventHandler ();
  };

};

#endif
