// Generated by dia2code
#ifndef INSTANCE__RULES__C
#define INSTANCE__RULES__C

#include "Rules.h"
#include "../state/State.h"
#include "algorithm"


namespace instance {


    Rules::Rules() {

    }

    Rules::Rules(state::State *state, bool aichar, bool aimonster) {
        this->state = state;
        AICharNeeded = aichar;
        AIMonsterNeeded = aimonster;
    }

    Rules::~Rules() {

    }

    bool Rules::getAICharNeeded() {
        return AICharNeeded;
    }

    void Rules::setAICharNeeded(bool aicharneeded) {
        AICharNeeded = aicharneeded;
    }

    bool Rules::getAIMonsterNeeded() {
        return AIMonsterNeeded;
    }

    void Rules::setAIMonsterNeeded(bool aimonsterneeded) {
        AIMonsterNeeded = aimonsterneeded;
    }

    std::vector<state::Element *> Rules::getTurnList() {
        return TurnList;
    }

    void Rules::setTurnList(std::vector<state::Element *> turnlist) {
        TurnList = turnlist;
    }

    void Rules::init() {
        std::vector<int> tab_agi_element;
        std::vector<state::Element*> tab_temp;
        int i,j;
        tab_agi_element.clear();
        tab_temp.clear();

        for(i=0; i<state->getElementList()->element.size();++i){
            tab_agi_element.push_back(state->getElementList()->element[i]->getAgility());
            tab_temp.push_back(state->getElementList()->element[i]);
        }

        i=0;j=1;
        while(i<state->getElementList()->element.size()){
            if(tab_agi_element[i]<tab_agi_element[j]){
                std::swap(tab_agi_element[i],tab_agi_element[j]);
                std::swap(tab_temp[i], tab_temp[j]);

            }
            ++j;
            if(j==state->getElementList()->element.size()){
                ++i;
                j=i+1;
            }
        }
        TurnList = tab_temp;

    }

    void Rules::NextTurn() {
        std::vector<state::Element*> tab_temp = TurnList;
        state::Element* element_temp = tab_temp.at(0);

        tab_temp.erase(tab_temp.begin());
        tab_temp.push_back(element_temp);

        TurnList = tab_temp;

    }
};

#endif