// Generated by dia2code
#ifndef INSTANCE__SCREEN__C
#define INSTANCE__SCREEN__C


namespace sf {
  class RenderWindow;
  class Texture;
}

#include <iostream>
#include "Screen.h"
#include "../state/Element.h"

namespace instance {

    Screen::~Screen()
    {
        //dtor
    }

    Screen::Screen(sf::RenderWindow* rw, render::Renderer* rd){

        window = rw;
        renderer = rd;

    }



    std::string Screen::run()
    {
        if(window->isOpen())
        {
            while(!needScreenChange)
            {
                while (window->pollEvent(event))
                {
                    if (event.type == sf::Event::Closed || sf::Keyboard::isKeyPressed(sf::Keyboard::Escape))
                    {
                        needScreenChange = true;
                        window->close();
                        std::cout << "System closed" << std::endl;
                        break;
                    }

                    eventHandler();
                }

                window->clear(sf::Color(0,0,0,255));
                renderer->render();
                window->display();
            }
            return nextScreen;
        }

    }

    void Screen::setNextScreen(std::string nScreen) {

    }
};

#endif
