// Generated by dia2code
#ifndef INSTANCE__SCREEN__C
#define INSTANCE__SCREEN__C


namespace sf {
  class RenderWindow;
  class Texture;
}

#include <iostream>
#include "Screen.h"
#include "../state/Element.h"

namespace instance {

    Screen::~Screen()
    {
        //dtor
    }

    Screen::Screen(sf::RenderWindow* rw, state::State* state, engine::Engine* engine){

        this->engine = engine;
        this->state = state;
        window = rw;

    }



    std::string Screen::run(render::Renderer* renderer, state::State* state)
    {
        if(window->isOpen())
        {
            while(!state->needScreenChange)
            {
                while (window->pollEvent(event))
                {
                    if (event.type == sf::Event::Closed)
                    {

                        state->needScreenChange = true;
                        window->close();
                        std::cout << "System closed" << std::endl;
                        break;
                    }

                    eventHandler();
                }

                window->clear(sf::Color(0,0,0,255));
                renderer->render();
                if (ui)
                    ui->display();
                window->display();
            }
            return state->nextScreen;
        }

    }

    void Screen::setNextScreen(std::string nScreen) {

    }
};

#endif
