// Generated by dia2code
#ifndef INSTANCE__SPELLUI__C
#define INSTANCE__SPELLUI__C


#include <state/Ability.h>
#include "SpellUI.h"
namespace sf {
  class RenderWindow;
};
namespace instance {
  class UI;

}


namespace instance {

    void SpellUI::display() {

    }

    SpellUI::~SpellUI() {

    }

    SpellUI::SpellUI(sf::RenderWindow *window, std::vector<state::Ability*> spells) {
        idstr = "SpellUI";

    }

    void SpellUI::menuItemSwitch(sf::Text &t1, sf::Text &t2) {
        t1.setColor(sf::Color::White);
        t2.setColor(sf::Color::Red);
    }

};

#endif
