// Generated by dia2code
#ifndef INSTANCE__SPELLUI__H
#define INSTANCE__SPELLUI__H

#include "SFML/Graphics.hpp"
#include "SFML/Audio.hpp"
#include <vector>
#include <string>
#include <map>

namespace sf {
  class RenderWindow;
};
namespace instance {
  class UI;
}

#include "UI.h"

namespace instance {

  /// class SpellUI - 
  class SpellUI : public instance::UI {
    // Attributes
  public:
    std::vector<sf::Text*> spellTexts;
    std::vector<std::string> spells;
    int maxSpell;
  protected:
    sf::RenderWindow* window;
    // Operations
  public:
    void display ();
    ~SpellUI ();
    SpellUI (sf::RenderWindow* window, std::map<int, bool> spells);
    void menuItemSwitch (sf::Text& t1, sf::Text& t2);
  };

};

#endif
