// Generated by dia2code
#ifndef INSTANCE__TARGETUI__H
#define INSTANCE__TARGETUI__H

#include "SFML/Graphics.hpp"
#include "SFML/Audio.hpp"

namespace sf {
  class RenderWindow;
};
namespace instance {
  class UI;
}

#include "UI.h"

namespace instance {

  /// class TargetUI - 
  class TargetUI : public instance::UI {
    // Attributes
  public:
    sf::Sprite* targetSprite;
  protected:
    sf::RenderWindow* window;
    // Operations
  public:
    void display ();
    ~TargetUI ();
    TargetUI (sf::RenderWindow* window, sf::Sprite* sprite);
    void menuItemSwitch (sf::Sprite* e1);
  };

};

#endif
