// Generated by dia2code
#ifndef INSTANCE__TARGETUI__C
#define INSTANCE__TARGETUI__C

#include "TargetUI.h"

namespace sf {
  class RenderWindow;
}

namespace instance {


    void TargetUI::display() {
        window->draw(*targetSprite);
    }

    TargetUI::~TargetUI() {

    }

    TargetUI::TargetUI(sf::RenderWindow *window, sf::Sprite* sprite) : window(window) {
        idstr = "TargetUI";
        sf::Texture* text = new sf::Texture();
        text->loadFromFile("res/arrow.png");
        text->setSmooth(true);
        targetSprite = new sf::Sprite();
        targetSprite->setTexture(*text);
        targetSprite->setScale(0.07,0.07);
        targetSprite->setPosition(sprite->getPosition().x-15,
                                  (float) (sprite->getPosition().y - 1.35 * sprite->getTexture()->getSize().y / 2));

    }

    void TargetUI::menuItemSwitch(sf::Sprite* e1) {
        targetSprite->setPosition(e1->getPosition().x-15,
                                  (float) (e1->getPosition().y - 1.35 * e1->getTexture()->getSize().y / 2));

    }
};

#endif
