// Generated by dia2code
#ifndef INSTANCE__UI__H
#define INSTANCE__UI__H

#include <string>
#include "SFML/Graphics.hpp"
#include "SFML/Audio.hpp"

namespace instance {

  /// class UI - 
  class UI {
    // Attributes
  public:
    std::string idstr;
  protected:
    sf::Font font;
    // Operations
  public:
    virtual void display () = 0;
  };

};

#endif
