// Generated by dia2code
#ifndef INSTANCE__WORLDMAP__H
#define INSTANCE__WORLDMAP__H

#include <vector>
#include "SFML/Graphics.hpp"
#include "SFML/Audio.hpp"

namespace state {
  class State;
};
namespace sf {
  class RenderWindow;
};
namespace instance {
  class Screen;
}

#include "Screen.h"

namespace instance {

  /// class Worldmap - Worldmap logic and rendering
  class Worldmap : public instance::Screen {
    // Attributes
  public:
    std::vector<state::Node*> tabNode;
  protected:
    state::State* state;
    // Operations
  public:
    Worldmap (sf::RenderWindow* window);
    virtual ~Worldmap ();
    void init (state::State* state);
    void eventHandler ();
    void setState (state::State* state);
  };

};

#endif
