// Generated by dia2code
#ifndef INSTANCE__WORLDMAP__H
#define INSTANCE__WORLDMAP__H

#include "SFML/Graphics.hpp"
#include "SFML/Audio.hpp"

namespace sf {
  class RenderWindow;
};
namespace instance {
  class Screen;
}

#include "Screen.h"

namespace instance {

  /// class Worldmap - Worldmap logic and rendering
  class Worldmap : public instance::Screen {
    // Operations
  public:
    Worldmap (sf::Font* font, sf::RenderWindow* window);
    virtual ~Worldmap ();
    void init ();
    void render ();
    void eventHandler ();
  };

};

#endif
