// Generated by dia2code
#ifndef INSTANCE__WORLDMAP__H
#define INSTANCE__WORLDMAP__H

#include "render/WorldmapRenderer.h"
#include "SFML/Graphics.hpp"
#include "SFML/Audio.hpp"

namespace render {
  class WorldmapRenderer;
};
namespace sf {
  class RenderWindow;
};
namespace state {
  class State;
};
namespace engine {
  class Engine;
};
namespace instance {
  class Screen;
}

#include "Screen.h"
#include "render/WorldmapRenderer.h"

namespace instance {

  /// class Worldmap - Worldmap logic and rendering
  class Worldmap : public instance::Screen {
    // Associations
    // Attributes
  public:
    render::WorldmapRenderer* renderer;
    // Operations
  public:
    Worldmap (sf::RenderWindow* window, render::WorldmapRenderer* renderer, state::State* state, engine::Engine* engine);
    virtual ~Worldmap ();
    void eventHandler ();
    void setState (state::State* state);
    void init ();
  };

};

#endif
