// Generated by dia2code
#ifndef INSTANCE__YOUENNUI__H
#define INSTANCE__YOUENNUI__H

#include "SFML/Graphics.hpp"
#include "SFML/Audio.hpp"

namespace sf {
  class Text;
}


namespace instance {

  /// class YouennUI - 
  class YouennUI {
    // Attributes
  protected:
    sf::Text abilities;
    sf::Text attack;
  };

};

#endif
