// Generated by dia2code
#ifndef STATE__ABILITY__H
#define STATE__ABILITY__H

#include <string>

namespace state {
  class Element;
}

#include "Element.h"

namespace state {

  /// class Ability - 
  class Ability : public state::Element {
    // Operations
  public:
    std::string LaunchAbility (std::string ability, Element* caster);
    std::string Fire ();
    std::string Thunder ();
    std::string H2O ();
    std::string Blizzard ();
    std::string Poison ();
    std::string Heal ();
  };

};

#endif
