// Generated by dia2code
#ifndef STATE__ABILITY__H
#define STATE__ABILITY__H

#include <string>
#include <map>

namespace state {
  class Element;
}

namespace state {

  /// class Ability - 
  class Ability {
    // Attributes
  public:
    std::map<std::string,bool> abilities;
    // Operations
  public:
    std::string LaunchAbility (std::string ability, Element* caster);
    std::map<std::string,bool> getAbility ();
    void setAbility (std::string ability);
    void unsetAbility (std::string ability);
    std::string Fire ();
    std::string Thunder ();
    std::string H2O ();
    std::string Blizzard ();
    std::string Poison ();
    std::string Heal ();
  };

};

#endif
