// Generated by dia2code
#ifndef STATE__ABILITY__H
#define STATE__ABILITY__H

#include <map>
#include <string>

namespace state {
  class Element;
}

#include "AbilityTypeID.h"

namespace state {

  /// class Ability - 
  class Ability {
    // Associations
    // Attributes
  protected:
    std::map<int,bool> abilities;
    // Operations
  public:
    std::string LaunchAbility (int ability, Element* caster);
    std::map<int,bool> getAbility ();
    void setAbility (int ability);
    void unsetAbility (int ability);
    std::string Brazier ();
    std::string Poison ();
    std::string Flare ();
    std::string FastHeal ();
    std::string Resurrection ();
    std::string Haste ();
    std::string Defender ();
    std::string CounterAttack ();
    std::string BattleCries ();
    std::string Bleeding ();
    std::string TripleAttack ();
    std::string DoubleUse ();
    std::string MultipleArrow ();
    std::string PoisonArrow ();
    std::string PiercingArrow ();
  };

};

#endif
