// Generated by dia2code
#ifndef STATE__ABILITYTYPEID__H
#define STATE__ABILITYTYPEID__H


namespace state {

  enum AbilityTypeID {
    BRazier     = 0,
    POISON     = 1,
    FLare     = 2,
    FAstHeal     = 3,
    REsurrection     = 4,
    HAste     = 5,
    DEfender     = 6,
    COunterAttack     = 7,
    BAttleCries     = 8,
    BLeeding     = 9,
    TRipleAttack     = 10,
    DOubleUse     = 11,
    MUltipleArrow     = 12,
    POisonArrow     = 13,
    PIercingArrow     = 14
  };

};

#endif
