// Generated by dia2code
#ifndef STATE__AELEMENTALLOC__C
#define STATE__AELEMENTALLOC__C


namespace state {
  class Element;
}

namespace state {

  /// class AElementAlloc - 
  class AElementAlloc {
    // Operations
  public:
    ~AElementAlloc (){}
    Element* newInstance (){}
  };

};

#endif
