// Generated by dia2code
#ifndef STATE__BLOB__C
#define STATE__BLOB__C


namespace state {
  class Monster;
}

#include "Monster.h"

namespace state {

  /// class Blob - 
  class Blob : public state::Monster {
    // Operations
  public:
    Blob(int playerLevel, int monsterSeed) : Monster(playerLevel, monsterSeed) {}
  };

};

#endif
