// Generated by dia2code
#ifndef STATE__BLOB__H
#define STATE__BLOB__H


namespace state {
  class Monster;
}

#include "Monster.h"

namespace state {

  /// class Blob - 
  class Blob : public state::Monster {
    // Operations
  public:
    Blob ();
  };

};

#endif
