// Generated by dia2code
#ifndef STATE__BOSS__C
#define STATE__BOSS__C

#include <string>

namespace state {
  class Element;
  class Monster;
}

#include "Element.h"
#include "Monster.h"

namespace state {

  /// class Boss - 
  class Boss : public state::Monster {
    // Attributes
  protected:
    int PowerToOverdrive;
    // Operations
  public:
    std::string Overdrive (Element target){}
  };

};

#endif
