// Generated by dia2code
#ifndef STATE__CHARACTER__C
#define STATE__CHARACTER__C

#include <string>

namespace state {
  class Element;
}

#include "SphereGrid.h"
#include "Element.h"

namespace state {

};

#endif
