// Generated by dia2code
#ifndef STATE__CHARACTER__H
#define STATE__CHARACTER__H

#include <string>

namespace state {
  class SphereGrid;
  class Item;
  class Element;
}

#include "SphereGrid.h"
#include "Item.h"
#include "Element.h"

namespace state {

  /// class Character - 
  class Character : public state::Element {
    // Associations
    // Attributes
  protected:
    //SphereGrid SphereGridInstance;
    int XPToNextLevel;
    int PowerToOverdrive;
    // Operations
  public:
    void LevelUp ();
    void GainXP (int xp);
    void UseItem (Item item);
    Character ();
    std::string Overdrive (Element target);
  };

};

#endif
