// Generated by dia2code
#ifndef STATE__CHARACTER__H
#define STATE__CHARACTER__H

#include <string>

namespace state {
  class Weapon;
  class Protection;
  class Item;
  class Element;
}

#include "Weapon.h"
#include "Protection.h"
#include "Item.h"
#include "Element.h"

namespace state {

  /// class Character - 
  class Character : public state::Element {
    // Associations
    // Attributes
  protected:
    SphereGrid SphereGridInstance;
    Weapon weapon;
    Protection protection;
    int XPToNextLevel;
    int PowerToOverdrive;
    // Operations
  public:
    void LevelUp ();
    void GainXP (int xp);
    void UseItem (Item item);
    Character ();
    virtual std::string Overdrive (Element target) = 0;
  };

};

#endif
