// Generated by dia2code
#ifndef STATE__CHARACTER__H
#define STATE__CHARACTER__H

#include <string>

namespace state {
  class SphereGrid;
  class Weapon;
  class Protection;
  class Item;
  class Element;
}

#include "SphereGrid.h"
#include "Weapon.h"
#include "Protection.h"
#include "Item.h"
#include "Element.h"

namespace state {

  /// class Character - 
  class Character : public state::Element {
    // Attributes
  protected:
    SphereGrid SphereGridInstance;
    Weapon weapon;
    Protection protection;
    int XPToNextLevel;
    int PowerToOverdrive;
    // Operations
  public:
    Character ();
    void LevelUp ();
    void GainXP (int xp);
    void UseItem (Item item);
    virtual std::string Overdrive (Element* target) = 0;
    SphereGrid getSphereGridInstance ();
    void setSphereGridInstance (SphereGrid spheregridinstance);
    Weapon getWeapon ();
    void setWeapon (Weapon weapon);
    Protection getProtection ();
    void setProtection (Protection protection);
    int getXpToNextLevel ();
    void setXpToNextLevel (int xptonextlevel);
    int getPowerToOverdrive ();
    void setPowerToOverdrive (int powertooverdrive);
    void managementOverdrive (std::string overdiveAbility);
  };

};

#endif
