// Generated by dia2code
#ifndef STATE__CLAUDE__H
#define STATE__CLAUDE__H

#include <string>

namespace state {
  class Element;
  class Character;
}

#include "Character.h"

namespace state {

  /// class Claude - 
  class Claude : public state::Character {
    // Operations
  public:
    Claude ();
    std::string Overdrive (Element* target);
  };

};

#endif
