// Generated by dia2code
#ifndef STATE__CLAUDE__C
#define STATE__CLAUDE__C

#include <string>

namespace state {
  class Element;
  class Character;
}

#include "Element.h"
#include "Character.h"

namespace state {

  /// class Claude - 
  class Claude : public state::Character {
    // Operations
  public:
    Claude (){}
    std::string Overdrive (Element target){}
  };

};

#endif
