// Generated by dia2code
#ifndef STATE__CLAUDE__C
#define STATE__CLAUDE__C

#include <string>

namespace state {
  class Element;
  class Character;
}

#include "Claude.h"

namespace state {


};

#endif
