// Generated by dia2code
#ifndef STATE__ELEMENTFACTORY__C
#define STATE__ELEMENTFACTORY__C


namespace state {
  class AElementAlloc;
  class ElementList;
}

#include "ElementFactory.h"

namespace state {


};

#endif
