// Generated by dia2code
#ifndef STATE__ELEMENTLIST__C
#define STATE__ELEMENTLIST__C


namespace state {
  class Element;
  class State;
}

#include "Element.h"
#include "State.h"

namespace state {

  /// class ElementList - 
  class ElementList {
    // Associations
  };

};

#endif
