// Generated by dia2code
#ifndef STATE__ELEMENTLIST__H
#define STATE__ELEMENTLIST__H

#include <vector>

namespace state {
  class Element;
  class State;
  class ElementFactory;
  class Observer;
}

#include "Observer.h"
#include "Element.h"
#include "State.h"

namespace state {

  /// class ElementList - 
  class ElementList : public state::Observer {
    // Associations
    // Attributes
  public:
    std::vector<Element*> element;
  protected:
    State* state;
    ElementFactory* factory;
    // Operations
  public:
    ElementList ();
  };

};

#endif
