// Generated by dia2code
#ifndef STATE__ELEMENTFACTORY__C
#define STATE__ELEMENTFACTORY__C

#include <map>

namespace state {
  class AElementAlloc;
  class ElementList;
}

#include "ElementFactory.h"

namespace state {

    const std::map<char, AElementAlloc *> &ElementFactory::getList() const {
      return list;
    }

    void ElementFactory::setList(const std::map<char, AElementAlloc *> &list) {
      ElementFactory::list = list;
    }
};

#endif
