// Generated by dia2code
#ifndef STATE__ELEMENTLIST__C
#define STATE__ELEMENTLIST__C

#include "ElementList.h"
#include "Character.h"
#include "Monster.h"

namespace state {

    ElementList::ElementList() {
        element.push_back(new state::Character("Claude"));
        element.push_back(new state::Character("Youenn"));
        element.push_back(new state::Monster(1, 2));
        element.push_back(new state::Monster(1, 2));
        element.push_back(new state::Monster(1, 2));
        element[2]->setName("Fire Elemental 1");
        element[3]->setName("Fire Elemental 2");
        element[4]->setName("Fire Elemental 3");

        element.at(0)->getAbility()->setAbility(0);
        element.at(0)->getAbility()->setAbility(1);
        element.at(0)->getAbility()->setAbility(3);

        element.at(1)->getAbility()->setAbility(0);
        element.at(1)->getAbility()->setAbility(1);
        element.at(1)->getAbility()->setAbility(3);


        Item* item = new Item();
        item->AddItem(16);

        element.at(2)->setItem(item);
        element.at(3)->setItem(item);
        element.at(4)->setItem(item);



    }

    ElementList *ElementList::clone() {
        ElementList* e = new ElementList(element);
        return e;
    }

    ElementList::ElementList(std::vector<Element *> elements) {
        for(unsigned int i=0;i<elements.size();++i){
            element.push_back( elements.at(i)->clone());
        }
    }

};

#endif
