// Generated by dia2code
#ifndef STATE__ELEMENTAL__H
#define STATE__ELEMENTAL__H


namespace state {
  class Monster;
}

#include "Monster.h"

namespace state {

  /// class Elemental - 
  class Elemental : public state::Monster {
    // Operations
  public:
    Elemental(int playerLevel, int monsterSeed);
  };

};

#endif
