// Generated by dia2code
#ifndef STATE__ELEMENTALLOC__C
#define STATE__ELEMENTALLOC__C


namespace state {
  class Element;
  class AElementAlloc;
}

#include "ElementAlloc.h"

namespace state {


};

#endif
