// Generated by dia2code
#ifndef STATE__EQUIPMENT__C
#define STATE__EQUIPMENT__C


namespace state {
  class Character;
}

#include "Character.h"

namespace state {

  /// class Equipment - Name serves as ID for bonuses during attack
  class Equipment {
    // Associations
    // Operations
  public:
    Equipment (){}
  };

};

#endif
