// Generated by dia2code
#ifndef STATE__FIREELEMENTAL__H
#define STATE__FIREELEMENTAL__H


namespace state {
  class Elemental;
}

#include "Elemental.h"

namespace state {

  /// class FireElemental - 
  class FireElemental : public state::Elemental {
    // Operations
  public:
    FireElemental ();
    ~FireElemental ();
  };

};

#endif
