// Generated by dia2code
#ifndef STATE__FIREELEMENTAL__C
#define STATE__FIREELEMENTAL__C


namespace state {
  class Elemental;
}

#include "Elemental.h"

namespace state {

  /// class FireElemental - 
  class FireElemental : public state::Elemental {
    // Operations
  public:
    FireElemental () : Elemental(0, 0) {}
  };

};

#endif
