// Generated by dia2code
#ifndef STATE__ICEELEMENTAL__H
#define STATE__ICEELEMENTAL__H


namespace state {
  class Elemental;
}

#include "Elemental.h"

namespace state {

  /// class IceElemental - 
  class IceElemental : public state::Elemental {
    // Operations
  public:
    IceElemental ();
  };

};

#endif
