// Generated by dia2code
#ifndef STATE__ICEELEMENTAL__C
#define STATE__ICEELEMENTAL__C


namespace state {
  class Elemental;
}

#include "Elemental.h"

namespace state {

  /// class IceElemental - 
  class IceElemental : public state::Elemental {
    // Operations
  public:
  };

};

#endif
