// Generated by dia2code
#ifndef STATE__ITEMTYPEID__H
#define STATE__ITEMTYPEID__H


namespace state {

  enum ItemTypeID {
    Potion     = 16,
    Revive     = 17,
    SuperPotion     = 18,
    Ether     = 19
  };

};

#endif
