// Generated by dia2code
#ifndef STATE__ITEMTYPEID__H
#define STATE__ITEMTYPEID__H


namespace state {

  enum ItemTypeID {
    Potion     = 0,
    Revive     = 1,
    SuperPotion     = 2,
    Ether     = 3
  };

};

#endif
