// Generated by dia2code
#ifndef STATE__ITEM__H
#define STATE__ITEM__H

#include <map>
#include <string>

namespace state {
  class Element;
}

#include "ItemTypeID.h"

namespace state {

  /// class Item - 
  class Item {
    // Associations
    // Attributes
  protected:
    std::map<int, int> items;
    // Operations
  public:
    void AddItem (int Id);
    std::string UseItem (Element* target, int id);
    std::map<int,int> getItem ();
    std::string POtion (Element* target);
    std::string SUperPotion (Element* target);
    std::string REvive (Element* target);
    std::string ETher (Element* target);
    void init ();
  };

};

#endif
