// Generated by dia2code
#ifndef STATE__JENOVA__H
#define STATE__JENOVA__H

#include <string>

namespace state {
  class Element;
  class Boss;
}

#include "Boss.h"

namespace state {

  /// class Jenova - 
  class Jenova : public state::Boss {
    // Operations
  public:
    Jenova ();
    ~Jenova ();
    std::string Overdrive (Element* target);
  };

};

#endif
