// Generated by dia2code
#ifndef STATE__JENOVA__C
#define STATE__JENOVA__C


namespace state {
  class Boss;
}

#include "Boss.h"

namespace state {

  /// class Jenova - 
  class Jenova : public state::Boss {
      Jenova() : Boss(0, 0) {}
  };

};

#endif
