// Generated by dia2code
#ifndef STATE__JENOVA__H
#define STATE__JENOVA__H


namespace state {
  class Boss;
}

#include "Boss.h"

namespace state {

  /// class Jenova - 
  class Jenova : public state::Boss {
      Jenova(int playerLevel, int monsterSeed) : Boss(playerLevel, monsterSeed) {}
  };

};

#endif
