// Generated by dia2code
#ifndef STATE__MAP__H
#define STATE__MAP__H


namespace state {
  class Node;
  class State;
}

#include "Node.h"
#include "State.h"

namespace state {

  /// class Map - 
  class Map {
    // Associations
    // Attributes
  protected:
    Node CurrentNode;
    // Operations
  public:
    /// Changes CurrentNode
    void NextNode ();
    void PreviousNode ();
    Map ();
  };

};

#endif
