// Generated by dia2code
#ifndef STATE__MONSTERTYPEID__C
#define STATE__MONSTERTYPEID__C


namespace state {

  enum MonsterTypeID {
    BLOB     = 0,
    SALAMANDER     = 1,
    FIRE_ELEMENTAL     = 2,
    WATER_ELEMENTAL     = 3,
    ICE_ELEMENTAL     = 4,
    THUNDER_ELEMENTAL     = 5,
    DOGNAR     = 6
  };

};

#endif
