// Generated by dia2code
#ifndef STATE__MONSTER__H
#define STATE__MONSTER__H


namespace state {
  class Element;
}

#include "Element.h"
#include "MonsterTypeID.h"

namespace state {

  /// class Monster - 
  class Monster : public state::Element {
    // Associations
    // Operations
  public:
    Monster (int playerLevel, int monsterSeed);
    ~Monster ();
    Monster ();
  };

};

#endif
