// Generated by dia2code
#ifndef STATE__MONSTER__C
#define STATE__MONSTER__C

#include "Monster.h"


namespace state {

    Monster::Monster() {
        Element();
    }

    Monster::Monster(int playerLevel, int monsterSeed) {
        //Implementer dans cette fonction switch case pour chaque monstre
        Element();
        switch (monsterSeed){
            case BLOB:
                PhysResist = 0.8;
                XPgiven = playerLevel*20;
                break;

            case SALAMANDER:
                MaxHP = HP = getMaxHP()+playerLevel*10;
                Strength = getStrength()+playerLevel;
                XPgiven = playerLevel*20;
                break;

            default:break;
        }


    }

    Monster::~Monster() {

    }

};

#endif
