// Generated by dia2code
#ifndef STATE__MONSTER__C
#define STATE__MONSTER__C

#include "Monster.h"


namespace state {

    Monster::Monster() :Element() {

    }

    Monster::Monster(int playerLevel, int monsterSeed) :Element(){
        //Implementer dans cette fonction switch case pour chaque monstre
        Id = monsterSeed;
        switch (monsterSeed){
            case BLOB:
                PhysResist = 0.8;
                break;

            case SALAMANDER:
                MaxHP = HP = getMaxHP()+playerLevel*10;
                Strength = getStrength()+playerLevel;
                break;

            default:break;
        }


    }

    Monster::~Monster() {

    }

    Element *Monster::clone() {
        Monster* m = new Monster();

        m->setHP(this->getHP());
        m->setMaxHP(this->getMaxHP());
        m->setMP(this->getMP());
        m->setMaxMP(this->getMaxMP());

        m->setStrength(this->getStrength());
        m->setAgility(this->getAgility());
        m->setIntelligence(this->getIntelligence());

        m->setAbility(this->getAbility());

        m->setId(this->getId());
        m->setName(this->getName());
        m->setItem(this->getItem()->clone());
        m->setLevel(this->getLevel());
        m->setDot(this->getDot());
        m->setIsCharacter(this->getIsCharacter());

        m->setPhysResist(this->getPhysResist());
        m->setMagicResist(this->getMagicResist());

        m->setXPgiven(XPgiven);

        return m;
    }

    void Monster::setXPgiven(int xpgiven) {
        XPgiven = xpgiven;
    }

};

#endif
