// Generated by dia2code
#ifndef STATE__NODELIST__H
#define STATE__NODELIST__H


namespace state {
  class Node;
  class NodeFactory;
  class State;
}

#include "NodeFactory.h"
#include "State.h"
#include "Node.h"

namespace state {

  /// class NodeList - 
  class NodeList {
    // Associations
    // Attributes
  protected:
    Node* CurrentNode;
    // Operations
  public:
    NodeList ();
    /// Changes CurrentNode
    void NextNode ();
    void PreviousNode ();
    Node* getCurrentNode ();
    void setCurrentNode (Node* currentnode);
  };

};

#endif
