// Generated by dia2code
#ifndef STATE__NODEFACTORY__H
#define STATE__NODEFACTORY__H

#include <map>

namespace state {
  class ANodeAlloc;
}

#include "ANodeAlloc.h"

namespace state {

  /// class NodeFactory - 
  class NodeFactory {
    // Associations
    // Attributes
  protected:
    std::map<char,ANodeAlloc*> list;
    // Operations
  public:
    ~NodeFactory ();
    Node* const newInstance (char id);
    void registerType (ANodeAlloc* a, char id);
  };

};

#endif
