// Generated by dia2code
#ifndef STATE__NODE__H
#define STATE__NODE__H

#include <string>

namespace state {
  class Node;
}


namespace state {

  /// class Node - 
  class Node {
    // Associations
    // Attributes
  protected:
    std::string NodeName;
    bool WasVisited;
    Node* Previous;
    Node* Next;
    // Operations
  public:
    void RandomEvent ();
    void StoryEvent ();
    Node (std::string NodeName);
    Node (Node previousNode, std::string NodeName);
  };

};

#endif
