// Generated by dia2code
#ifndef STATE__NODE__H
#define STATE__NODE__H


namespace state {
  class Node;
}


namespace state {

  /// class Node - 
  class Node {
    // Associations
    // Attributes
  protected:
    int Id;
    bool WasVisited;
    Node* Previous;
    Node* Next;
    // Operations
  public:
    Node (int id);
    Node (Node* previousNode, int id);
    void RandomEvent ();
    void StoryEvent ();
    int getId ();
    void setId (int id);
    bool getWasVisited ();
    void setWasVisited (bool wasvisited);
    Node* getPreviousNode ();
    void setPreviousNode (Node* previousnode);
    Node* getNextNode ();
    void setNextNode (Node* nextnode);
  };

};

#endif
