// Generated by dia2code
#ifndef STATE__NODELIST__C
#define STATE__NODELIST__C


namespace state {
  class Node;
  class NodeFactory;
  class State;
}

#include "NodeList.h"

namespace state {

    Node *NodeList::getCurrentNode() const {
      return CurrentNode;
    }

    void NodeList::setCurrentNode(Node *CurrentNode) {
      NodeList::CurrentNode = CurrentNode;
    }

};

#endif
