// Generated by dia2code
#ifndef STATE__NODE__C
#define STATE__NODE__C


#include "Node.h"

namespace state {
  class Node;

    Node::Node(int id) {
        Id = id;
        WasVisited = false;
    }

    Node::Node(Node* previousNode, int id) {
        Id = id;
        WasVisited = false;
        Previous = previousNode;
    }

    int Node::getId() {
        return Id;
    }

    void Node::setId(int id) {
        Id = id;
    }

    bool Node::getWasVisited() {
        return WasVisited;
    }

    void Node::setWasVisited(bool wasvisited) {
        WasVisited = wasvisited;
    }

    Node *Node::getPreviousNode() {
        return Previous;
    }

    void Node::setPreviousNode(Node *previousnode) {
        Previous = previousnode;
    }

    Node *Node::getNextNode() {
        return Next;
    }

    void Node::setNextNode(Node *nextnode) {
        Next = nextnode;
    }

}


namespace state {


};

#endif
