// Generated by dia2code
#ifndef STATE__NODEALLOC__H
#define STATE__NODEALLOC__H


namespace state {
  class Element;
  class ANodeAlloc;
}

#include "ANodeAlloc.h"

namespace state {

  /// class NodeAlloc - 
  template <  class E,   typename ID>
  class NodeAlloc : public state::ANodeAlloc {
    // Attributes
  protected:
    ID id;
    // Operations
  public:
    NodeAlloc (ID id);
    Element* newInstance ();
  };

};

#endif
