// Generated by dia2code
#ifndef STATE__NODE__H
#define STATE__NODE__H

#include <string>

namespace state {
  class Node;
}


namespace state {

  /// class Node - 
  class Node {
    // Associations
    // Attributes
  protected:
    std::string NodeName;
    bool WasVisited;
    Node* Previous;
    Node* Next;
    // Operations
  public:
    Node (std::string NodeName);
    Node (Node previousNode, std::string NodeName);
    void RandomEvent ();
    void StoryEvent ();
    std::string getNodeName ();
    void setNodeName (std::string nodename);
    bool getWasVisited ();
    void setWasVisited (bool wasvisited);
    Node* getPreviousNode ();
    void setPreviousNode (Node* previousnode);
    Node* getNextNode ();
    void setNextNode (Node* nextnode);
  };

};

#endif
