// Generated by dia2code
#ifndef STATE__OBSERVABLE__H
#define STATE__OBSERVABLE__H

#include <vector>

namespace state {
  class StateObserver;
  class StateEvent;
}

#include "StateObserver.h"

namespace state {

  /// class Observable - 
  class Observable {
    // Associations
    // Attributes
  protected:
    std::vector<StateObserver*> observers;
    // Operations
  public:
    Observable ();
    void registerObsever (StateObserver* etat_observe);
    void unregisterObserver (StateObserver* etat_observe);
    void notifyObservers (StateEvent* etat);
  };

};

#endif
