// Generated by dia2code
#ifndef STATE__OBSERVER__C
#define STATE__OBSERVER__C

#include "Observer.h"

namespace state {
  class State;

    Observer::Observer() {

    }
}

namespace state {

 

};

#endif
