// Generated by dia2code
#ifndef STATE__OBSERVER__H
#define STATE__OBSERVER__H

#include <vector>

namespace state {
  class State;
}

namespace state {

  /// class Observer - 
  class Observer {
    // Attributes
  protected:
    std::vector<State*> observers;
    // Operations
  public:
    Observer ();
    void registerObserver (State* etat_observe);
    void unregisterObserver (State* etat_observe);
    void notifyObservers (State* etat);
  };

};

#endif
