// Generated by dia2code
#ifndef STATE__PROTECTION__H
#define STATE__PROTECTION__H


namespace state {
  class Equipment;
}

#include "Equipment.h"

namespace state {

  /// class Protection - 
  class Protection : public state::Equipment {
    // Operations
  public:
    Protection ();
  };

};

#endif
