// Generated by dia2code
#ifndef STATE__SALAMANDER__H
#define STATE__SALAMANDER__H


namespace state {
  class Monster;
}

#include "Monster.h"

namespace state {

  /// class Salamander - 
  class Salamander : public state::Monster {
    // Operations
  public:
    Salamander ();
  };

};

#endif
