// Generated by dia2code
#ifndef STATE__SALAMANDER__C
#define STATE__SALAMANDER__C


namespace state {
  class Monster;
}

#include "Monster.h"

namespace state {

  /// class Salamander - 
  class Salamander : public state::Monster {
    // Operations
  public:
    Salamander(int playerLevel, int monsterSeed) : Monster(playerLevel, monsterSeed) {}
  };

};

#endif
