// Generated by dia2code
#ifndef STATE__SPHEREGRID__H
#define STATE__SPHEREGRID__H

#include <vector>
#include <string>

namespace state {
  class Character;
}

#include "Character.h"
#include "SphereGridTypeID.h"

namespace state {

  /// class SphereGrid - 
  class SphereGrid {
    // Associations
    // Attributes
  protected:
    std::vector<int> tab_comp;
    int Position;
    Character* character;
    int Id;
    // Operations
  public:
    SphereGrid ();
    SphereGrid (int id, Character* character);
    ~SphereGrid ();
    std::vector<int> getTab ();
    void setTab (std::vector<int> tab);
    int getPosition ();
    void setPosition (int position);
    void LevelUp ();
    std::vector<int> CreateTab (int id);
    std::string SwitchTab ();
  };

};

#endif
