// Generated by dia2code
#ifndef STATE__SPHEREGRIDTYPEID__H
#define STATE__SPHEREGRIDTYPEID__H


namespace state {

  enum SphereGridTypeID {
    BlackMage     = 0,
    WhiteMage     = 1,
    War     = 2,
    Rogue     = 3,
    Hunt     = 4
  };

};

#endif
