// Generated by dia2code
#ifndef STATE__SPHEREGRID__HL
#define STATE__SPHEREGRID__HL


namespace state {
  class Character;
}

#include "Character.h"

namespace state {

  /// class SphereGrid - 
  class SphereGrid {
    // Associations
  };

};

#endif
