// Generated by dia2code
#ifndef STATE__STATETYPEID__H
#define STATE__STATETYPEID__H


namespace state {

  enum StateTypeID {
    MENU     = 0,
    CITY_CHANGED     = 1,
    FIGHT_ENDED     = 2,
    REST_ENDED     = 3
  };

};

#endif
