// Generated by dia2code
#ifndef STATE__STATEEVENTID__H
#define STATE__STATEEVENTID__H


namespace state {

  enum StateEventId {
    MENU     = 0,
    CITY_CHANGED     = 1,
    FIGHT_ENDED     = 2,
    REST_ENDED     = 3
  };

};

#endif
