// Generated by dia2code
#ifndef STATE__STATEEVENT__H
#define STATE__STATEEVENT__H


namespace state {
  class State;
  class StateObserver;
}

#include "StateEventId.h"
#include "StateObserver.h"

namespace state {

  /// class StateEvent - 
  class StateEvent {
    // Attributes
  protected:
    State* state;
    // Operations
  public:
    StateEvent (State* state, StateEventId id);
    ~StateEvent ();
    const bool operator== (StateEventId id);
    const bool operator!= (StateEventId id);
    State* getState ();
    void setState (State* state);
  };

};

#endif
