// Generated by dia2code
#ifndef STATE__THUNDERELEMENTAL__C
#define STATE__THUNDERELEMENTAL__C


namespace state {
  class Elemental;
}

#include "Elemental.h"

namespace state {

  /// class ThunderElemental - 
  class ThunderElemental : public state::Elemental {
    // Operations
  public:
    ThunderElemental () : Elemental(0, 0) {}
  };

};

#endif
