// Generated by dia2code
#ifndef STATE__THUNDERELEMENTAL__H
#define STATE__THUNDERELEMENTAL__H


namespace state {
  class Elemental;
}

#include "Elemental.h"

namespace state {

  /// class ThunderElemental - 
  class ThunderElemental : public state::Elemental {
    // Operations
  public:
    ThunderElemental ();
    ~ThunderElemental ();
  };

};

#endif
