// Generated by dia2code
#ifndef STATE__VARYTHRIX__H
#define STATE__VARYTHRIX__H


namespace state {
  class Boss;
}

#include "Boss.h"

namespace state {

  /// class Varythrix - 
  class Varythrix : public state::Boss {
  };

};

#endif
