// Generated by dia2code
#ifndef STATE__WANSDICH__H
#define STATE__WANSDICH__H


namespace state {
  class Boss;
}

#include "Boss.h"

namespace state {

  /// class Wansdich - 
  class Wansdich : public state::Boss {
      Wansdich(int playerLevel, int monsterSeed) : Boss(playerLevel, monsterSeed) {}
  };

};

#endif
