// Generated by dia2code
#ifndef STATE__WANSDICH__C
#define STATE__WANSDICH__C


namespace state {
  class Boss;
}

#include "Boss.h"

namespace state {

  /// class Wansdich - 
  class Wansdich : public state::Boss {
  };

};

#endif
