// Generated by dia2code
#ifndef STATE__WATERELEMENTAL__C
#define STATE__WATERELEMENTAL__C


namespace state {
  class Elemental;
}

#include "Elemental.h"

namespace state {

  /// class WaterElemental - 
  class WaterElemental : public state::Elemental {
    // Operations
  public:
    WaterElemental () : Elemental(0, 0) {}
  };

};

#endif
