// Generated by dia2code
#ifndef STATE__WATERELEMENTAL__H
#define STATE__WATERELEMENTAL__H


namespace state {
  class Elemental;
}

#include "Elemental.h"

namespace state {

  /// class WaterElemental - 
  class WaterElemental : public state::Elemental {
    // Operations
  public:
    WaterElemental ();
  };

};

#endif
