// Generated by dia2code
#ifndef STATE__WEAPON__H
#define STATE__WEAPON__H


namespace state {
  class Equipment;
}

#include "Equipment.h"

namespace state {

  /// class Weapon - 
  class Weapon : public state::Equipment {
    // Operations
  public:
    Weapon ();
  };

};

#endif
