// Generated by dia2code
#ifndef STATE__YOUENN__C
#define STATE__YOUENN__C

#include <string>

namespace state {
  class Element;
  class Character;
}

#include "Youenn.h"

namespace state {

};

#endif
