// Generated by dia2code
#ifndef STATE__YOUENN__H
#define STATE__YOUENN__H

#include <string>

namespace state {
  class Element;
  class Character;
}

#include "Element.h"
#include "Character.h"

namespace state {

  /// class Youenn - 
  class Youenn : public state::Character {
    // Operations
  public:
    Youenn ();
    std::string Overdrive (Element target);
  };

};

#endif
