// Generated by dia2code
#ifndef __INSTANCE__H
#define __INSTANCE__H

#include "instance/Screen.h"
#include "instance/Worldmap.h"
#include "instance/Intro.h"
#include "instance/Fight.h"
#include "instance/Inn.h"
#include "instance/Application.h"
#include "instance/Rules.h"
#include "instance/Action.h"
#endif
